pool:
  name: Pool_12

trigger:
  branches:
    include:
      - main
      - feature/*

stages:
  - stage: TerraformStage
    displayName: "Terraform Stage"
    jobs:
      - job: validate
        displayName: "Validate"
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Service_connection12'
              backendAzureRmStorageAccountName: 'pipelinetfstate'
              backendAzureRmContainerName: 'container'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
