pool: Pool_12

trigger:
-main
-feature/*

stages:
  - stage: 
    jobs:
      - job: validate
        displayName: validate
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'Service_connection12'
            backendAzureRmStorageAccountName: 'pipelinetfstate'
            backendAzureRmContainerName: 'container'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'